apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-impact-ing
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: traefik
  rules:
  - host: space-impact.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: space-impact-svc
            port:
              number: 80
  tls:
  - hosts:
    - space-impact.local
    secretName: space-impact-tls  # created by cert-manager